skill-tree:
  acquired-level:
        material: "160:13"
  unacquired-level:
        material: "160:14"
skills:
  mining:
    display-item:
      material: "DIAMOND_PICKAXE"
      name: "&aMining &6%level%&7/&6%levelCap%"
      lore: "&7Click to view mining skill tree &6%currentExp%&7/&6%nextExp%"
    level-up:
      # linear function -> amtNeededToLevelup = multiplier * level + base
      base: 200
      multiplier: 200
    level-cap: 30
    gui-title: "&aMining"
    rewards:
      1: "&aThis is level 1"
    # format is -> BLOCK;EXP
    blocks:
      - STONE;1
      - DIAMOND_ORE;4
      - 15;2
    bonus:
      # this is a linear function -> increasedDamage = multiplier * level + damage
      damage-multiplier: 1
      # percentage varies until 100
      double-ore-base: 1
      # this is a linear function -> doubleOreChance = multiplier * level + doubleOreBase
      double-ore-multiplier: 1
  combat:
    display-item:
      material: "DIAMOND_SWORD"
      name: "&aCombat &6%level%&7/&6%levelCap%"
      lore: "&7Click to view combat skill tree &6%currentExp%&7/&6%nextExp%"
    level-up:
      # linear function -> amtNeededToLevelup = multiplier * level + base
      base: 200
      multiplier: 200
    level-cap: 30
    gui-title: "&aCombat"
    rewards:
      1: "&aThis is level 1"
    entities:
      - PLAYER;5
      - ZOMBIE;2
      - SHEEP;1
      - SPIDER;3
    bossmobs:
      - ENTITY1;2
      - ENTITY2;2
      - ENTITY3;2
    bonus:
      # health increases by this amount every level
      health-increment: 20
      # percentage varies until 100
      double-damage-base: 25
      # this is a linear function -> doubleDmgChance = multiplier * level + doubleDmgBase
      double-damage-multiplier: 1
  foraging:
    display-item:
      material: "DIAMOND_AXE"
      name: "&aForaging &6%level%&7/&6%levelCap%"
      lore: "&7Click to view foraging skill tree &6%currentExp%&7/&6%nextExp%"
    level-up:
      # linear function -> amtNeededToLevelup = multiplier * level + base
      base: 200
      multiplier: 200
    level-cap: 30
    gui-title: "&aForaging"
    rewards:
      1: "&aThis is level 1"
    bonus:
      # this is a flat multiplier
      speed-multiplier: 1.5
      # percentage varies until 100
      double-wood-base: 25
      # this is a linear function -> doubleWoodChance = multiplier * level + doubleWoodBase
      double-wood-multiplier: 1
  fishing:
    display-item:
      material: "FISHING_ROD"
      name: "&aFishing &6%level%&7/&6%levelCap%"
      lore: "&7Click to view fishing skill tree &6%currentExp%&7/&6%nextExp%"
    level-up:
      # linear function -> amtNeededToLevelup = multiplier * level + base
      base: 200
      multiplier: 200
    level-cap: 30
    gui-title: "&aFishing"
    rewards:
      1: "&aThis is level 1"
    bonus:
      # percentage varies until 100
      better-item-base: 25
      # this is a linear function -> itemChance = multiplier * level + itemBase
      better-item-multiplier: 1
    item-pool:
      - STONE
      - DIAMOND
      - IRON_INGOT
  farming:
    display-item:
      material: "DIAMOND_HOE"
      name: "&aFarming &6%level%&7/&6%levelCap%"
      lore: "&7Click to view farming skill tree &6%currentExp%&7/&6%nextExp%"
    level-up:
      # linear function -> amtNeededToLevelup = multiplier * level + base
      base: 200
      multiplier: 200
    level-cap: 30
    gui-title: "&aFarming"
    rewards:
      1: "&aThis is level 1"
    bonus:
      # amt of health regenerated
      regen-base: 1
      # this is a linear function -> regenAmt = multiplier * level + regenBase
      regen-multiplier: 1
      # percentage varies until 100
      double-crop-base: 25
      # this is a linear function -> doubleCropChance = multiplier * level + doubleCropBase
      double-crop-multiplier: 1
  craftsmanship:
    display-item:
      material: "WORKBENCH"
      name: "&aCraftsmanship &6%level%&7/&6%levelCap%"
      lore: "&7Click to view craftsmanship skill tree &6%currentExp%&7/&6%nextExp%"
    level-up:
      # linear function -> amtNeededToLevelup = multiplier * level + base
      base: 200
      multiplier: 200
    level-cap: 30
    gui-title: "&aCraftsmanship"
    rewards:
      1: "&aThis is level 1"
    bonus:
      luck-increment: 2
  blacksmithing:
    display-item:
      material: "OBSIDIAN"
      name: "&aBlacksmithing &6%level%&7/&6%levelCap%"
      lore: "&7Click to view blacksmithing skill tree &6%currentExp%&7/&6%nextExp%"
    level-up:
      # linear function -> amtNeededToLevelup = multiplier * level + base
      base: 200
      multiplier: 200
    level-cap: 30
    gui-title: "&aBlacksmithing"
    rewards:
      1: "&aThis is level 1"
    bonus:
      # amt of mana regenerated
      mana-regen-base: 1
      # this is a linear function -> regenAmt = multiplier * level + regenBase
      mana-regen-multiplier: 1
  defense:
    display-item:
      material: "BEACON"
      name: "&aDefense &6%level%&7/&6%levelCap%"
      lore: "&7Click to view defense skill tree &6%currentExp%&7/&6%nextExp%"
    level-up:
      # linear function -> amtNeededToLevelup = multiplier * level + base
      base: 200
      multiplier: 200
    level-cap: 30
    gui-title: "&aDefense"
    rewards:
      1: "&aThis is level 1"
    bonus:
      # amt of dmg decreased
      defense-base: 1
      # this is a linear function -> dmgDecreased = multiplier * level + defenseBase
      defense-multiplier: 1
  runecrafting:
    display-item:
      material: "EMERALD"
      name: "&aRunecrafting &6%level%&7/&6%levelCap%"
      lore: "&7Click to view runecrafting skill tree &6%currentExp%&7/&6%nextExp%"
    level-up:
      # linear function -> amtNeededToLevelup = multiplier * level + base
      base: 200
      multiplier: 200
    level-cap: 30
    gui-title: "&aRunecrafting"
    rewards:
      1: "&aThis is level 1"
    bonus:
      # amt of wisdom
      wisdom-base: 1
      # this is a linear function -> wisdomAmt =  multiplier * level + wisdomBase
      wisdom-multiplier: 1